fix getPointsForMessage method
USHIN-Inc/ushin-db pull request #18
Opened 2020-12-23 08:33 UTC by josephmturner

(it now returns reference points for each log in the reference history of all reference points contained in the message)

2020-12-23 08:52 UTC, josephmturner commented
This commit is necessary for this ushin-ui-components [PR](https://github.com/USHIN-Inc/ushin-ui-components/pull/154).

2020-12-23 17:09 UTC, RangerMauve requested changes
This looks good, I think we might be able to get rid of most of the logic if we use `message.allPoints` instead of calculating all the points here.

2020-12-23 17:09 UTC, RangerMauve commented on index.js
> +    const pointIds = [main, ...Object.values(shapes).flat()];
Maybe we should just use the `allPoinnts` array from the message instead of `main` and `shapes`? :P

2020-12-24 08:05 UTC, josephmturner commented
Works great! We can delete the extra comment in a later commit :)

2020-12-24 08:05 UTC, merged